# Copyright 2026 Odoo Community Association (OCA)
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl).
"""Load a noupdate_changes.xml without overwriting customized mail/sms templates.

Plain ``openupgrade.load_data`` rewrites every field present in the file, which
silently destroys local edits of ``mail.template`` / ``sms.template`` records
(they are noupdate). ``load_data_keep_customized`` only overwrites a field when
the value stored in the database (en_US) is the pristine Odoo 19 value, whose
hash is shipped in ``pristine_19_noupdate.json`` next to the xml file
(generated by migration20/tools/gen_pristine_templates.py from a pristine 19
install). A customized field is removed from the file before loading: its value
and its translations stay untouched, and a WARNING is logged. ``force`` lists (xmlid, field) pairs that must be
overwritten even when customized (owner decision, logged at INFO).
Translations of the translatable fields that were really overwritten are
dropped (only the en_US key is kept) so that the .po files of 20 are loaded.
"""
import hashlib
import io
import json
import logging
import os
import re

from lxml import etree
from openupgradelib import openupgrade

from odoo import tools

_logger = logging.getLogger(__name__)

TABLES = {"mail.template": "mail_template", "sms.template": "sms_template"}


def normalize(value):
    """Whitespace-insensitive form of a template value (keep in sync with
    migration20/tools/gen_pristine_templates.py)."""
    value = re.sub(r"\s+", " ", value or "")
    return re.sub(r"\s*([<>])\s*", r"\1", value).strip()


def digest(value):
    return hashlib.sha1(normalize(value).encode()).hexdigest()


def _read(module, filename):
    fp = openupgrade._file_open(module, filename)
    try:
        data = fp.read()
    finally:
        fp.close()
    return data.encode() if isinstance(data, str) else data


def _current_value(cr, table, column, res_id):
    """Return (en_US or plain value as text, is_jsonb) of a column."""
    cr.execute(
        "SELECT data_type FROM information_schema.columns "
        "WHERE table_name = %s AND column_name = %s",
        (table, column),
    )
    row = cr.fetchone()
    if not row:
        return None, False
    jsonb = row[0] == "jsonb"
    expr = f'"{column}"->>\'en_US\'' if jsonb else f'"{column}"::text'
    cr.execute(f'SELECT {expr} FROM "{table}" WHERE id = %s', (res_id,))  # noqa: E8103
    row = cr.fetchone()
    return (row[0] if row else None), jsonb


def load_data_keep_customized(
    env, module, filename, pristine_filename="pristine_19_noupdate.json", force=()
):
    """Load ``filename`` of ``module`` (same as ``openupgrade.load_data``) but keep
    the customized fields of template records.

    :param pristine_filename: json file next to ``filename`` mapping
        ``"module.xmlid" -> {field: [pristine hashes]}``
    :param force: iterable of ``("module.xmlid", field)`` pairs overwritten with the
        file value (and their translations dropped) even when customized
    :return: list of ``(xmlid, field)`` kept because customized
    """
    cr = env.cr
    base = os.path.dirname(filename)
    pristine = json.loads(_read(module, os.path.join(base, pristine_filename)))
    root = etree.fromstring(_read(module, filename))
    kept, overwritten = [], []
    for rec in root.iter("record"):
        model = rec.get("model")
        table = TABLES.get(model)
        if not table:
            continue
        xmlid = rec.get("id")
        mod, name = xmlid.split(".", 1) if "." in xmlid else (module, xmlid)
        cr.execute(
            "SELECT res_id FROM ir_model_data "
            "WHERE module = %s AND name = %s AND model = %s",
            (mod, name, model),
        )
        row = cr.fetchone()
        if not row:
            continue  # deleted by the user: the file recreates it as is
        res_id = row[0]
        hashes = pristine.get("%s.%s" % (mod, name), {})
        for fld in list(rec.findall("field")):
            column = fld.get("name")
            if column not in hashes:
                continue  # not a plain column or unknown pristine value: apply
            value, jsonb = _current_value(cr, table, column, res_id)
            is_forced = ("%s.%s" % (mod, name), column) in force
            if is_forced and digest(value) not in hashes[column]:
                _logger.info(
                    "customized template overwritten by owner decision: %s.%s",
                    "%s.%s" % (mod, name),
                    column,
                )
            if is_forced or digest(value) in hashes[column]:
                if jsonb:
                    overwritten.append((table, column, res_id))
                continue
            rec.remove(fld)
            kept.append(("%s.%s" % (mod, name), column))
            _logger.warning(
                "customized template kept: %s.%s (DB value differs from the "
                "pristine 19 one; merge the 20 version by hand)",
                "%s.%s" % (mod, name),
                column,
            )
    fp = io.StringIO(etree.tostring(root, encoding="unicode"))
    fp.name = None
    _logger.info("%s: loading %s (customized fields kept: %d)", module, filename, len(kept))
    tools.convert_xml_import(env, module, fp, {}, mode="init")
    for table, column, res_id in overwritten:
        openupgrade.logged_query(
            cr,
            f"""
            UPDATE "{table}" SET "{column}" = jsonb_build_object(
                'en_US', "{column}"->'en_US')
            WHERE id = %s AND "{column}" ? 'en_US'
                AND (SELECT count(*) FROM jsonb_object_keys("{column}")) > 1
            """,  # noqa: E8103
            (res_id,),
        )
    return kept
